theme: jekyll-theme-architect
title: To be Decided :)
description: Hi! I think it would be a waste of opportunity for me not to have a corner where I write my thoughts about everything and share my ideas and projects. Will develop on this soon...
